version: '3.3'
services:
  web:
       build:
               context: ./php/online-shopping-system
               dockerfile: Dockerfile
       container_name: php_app1
       volumes:
          - ./php/online-shopping-system:/var/www/html
       depends_on: 
         - db  
       ports:
         - 8080:90
  db:
          container_name: mysql2
          image: mysql:latest
          command: --default-authentication-plugin=mysql_native_password
          restart: always  
          volumes:
             - ./php/online-shopping-system/database/onlineshop.sql:/docker-entrypoint-initdb.d/onlineshop.sql
          ports:
           - 6034:3308
